### PR TITLE
Updated and fixed Polish translation

### PR DESCRIPTION
**Pull request by PatrykMis**
I have fixed some typos and translation mistakes in Polish readme.md and plugin interface.

### CODE REVIEW

**Comment by zstanecic** [comment]
Hi Patryk,
This addon is part of the NVDA translation system on assembla.
If you want to give suggestions or join the translation and help, you can do so.
Translations for this addon are merged every fiday.
So, please suggest me the changes privatelly and i will be happy to make them incorporeted, as i am one of the NVDA polish translators.
Best and have a nice day,]
Zvonimir

**Comment by zstanecic** [comment]
so, the first thing which i recommend is to close this pull request.
Translation corrections are done in another repository, and these are fetched every friday.

**Comment by PatrykMis** [comment]
Ok, thank you for pointing me to the right direction - I didn't know that.
So, if you are maintainer, you can review changes in this pull request and encorporate them in right place - some of them are important, some are cosmetic.

**Comment by zstanecic** [comment]
Hi,

I will download this and incorporate these today.

**Pull request closed without merging**
